BUG: DataImporter: Fix error on application exit removing uneeded cleanup() call
Since the "cleanup()" function is called on module unloading, this commit
removes the redundant call in the destructor and fixes the following error:

Traceback (most recent call last):
    File "/path/to/SlicerSALT-SuperBuild/Slicer-build/lib/SlicerSALT-4.11/qt-scripted-modules/DataImporter.py", line 579, in __del__
      self.cleanup()
    File "/path/to/SlicerSALT-SuperBuild/Slicer-build/lib/SlicerSALT-4.11/qt-scripted-modules/DataImporter.py", line 574, in cleanup
      self.resetSubjectsTable()
    File "/path/to/SlicerSALT-SuperBuild/Slicer-build/lib/SlicerSALT-4.11/qt-scripted-modules/DataImporter.py", line 666, in resetSubjectsTable
      self.SubjectsTableWidget.setRowCount(0)
  ValueError: Trying to call 'setRowCount' on a destroyed QTableWidget object