COMP: Disable unused WebServer module to workaround startup error
When launching a Slicer (or Slicer-based) application built with
`Slicer_BUILD_DICOM_SUPPORT` set to `OFF`, the application fails to
load the `WebServer` module due to a missing dependency:

```
Traceback (most recent call last):
  ...
  File "/work/salt/build_59/Slicer-build/lib/SlicerSALT-5.9/qt-scripted-modules/WebServer.py", line 18, in <module>
    from WebServerLib.BaseRequestHandler import BaseRequestHandler, BaseRequestLoggingFunction
  File "/work/salt/build_59/Slicer-build/lib/SlicerSALT-5.9/qt-scripted-modules/WebServerLib/__init__.py", line 2, in <module>
    from .DICOMRequestHandler import DICOMRequestHandler
  File "/work/salt/build_59/Slicer-build/lib/SlicerSALT-5.9/qt-scripted-modules/WebServerLib/DICOMRequestHandler.py", line 2, in <module>
    import pydicom
ModuleNotFoundError: No module named 'pydicom'
loadSourceAsModule - Failed to load file "/work/salt/build_59/Slicer-build/lib/SlicerSALT-5.9/qt-scripted-modules/WebServer.py"  as module "WebServer" !
Fail to instantiate module  "WebServer"
The following modules failed to be instantiated:
   WebServer
```

This happens because `WebServerLib/DICOMRequestHandler.py` unconditionally
imports `pydicom`, even when DICOM support is explicitly disabled at build
time.

This commit works around the issue by disabling the WebServer module.